#!/bin/bash

dp0="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${dp0}/base.sh

TITLE=${PROJECT_BASE##*/}
PATH=${ONE_BASE}/bin:${PATH}
PS1='\[\e]2;[${TITLE}]\a\](${TITLE}) \W $ '

source ${ONE_BASE}/bin/set-env

if [ "$0" == "$( readlink -f ${PROJECT_BASE}/dev-sh )" ]; then
  if [ "${PLATFROM}" == "OSX" ]; then
	BestTerminal="open -a Terminal.app" 
  elif [ "${PLATFROM}" == "Linux" ]; then
	BestTerminal="$( update-alternatives --query x-terminal-emulator | grep Best | awk '{print $2}' ) -e"
  fi
  
  CURRENT_DIR="$(pwd)"
  cd ${PROJECT_BASE}
  ${BestTerminal} "${BASH} --rcfile \"${BASH_SOURCE[0]}\" -i"
  cd ${CURRENT_DIR}  

elif [ "$0" == "${BASH}" ]; then
  source ~/.bashrc
  cat ${ONE_CONFIG_BASE}/help.txt
else
  if [ -z "$1" ]; then
    CURRENT_DIR="$(pwd)"
    cd ${PROJECT_BASE}
    ${BASH} --rcfile "${BASH_SOURCE[0]}" -i
    cd ${CURRENT_DIR}
  else
    CURRENT_DIR="$(pwd)"
    cd ${PROJECT_BASE}
    ${BASH} -c "$1"
    cd ${CURRENT_DIR}
  fi
fi