#!/bin/bash

dp0="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${dp0}/base.sh

_SET_ENV=${PROJECT_BASE}/bin/apps/set-env.sh
if [ -f ${_SET_ENV} ]; then
    source "${_SET_ENV}"
fi

_SET_ENV=${PROJECT_BASE}/config/one/set-env.sh
if [ -f ${_SET_ENV} ]; then
    source "${_SET_ENV}"
fi

_SET_ENV=
