#!/usr/bin/env bash

verbose=2

# find the real ssh/scp executable
program=$(basename "$0")
if [ "${program}" == ssh ]; then
    program=ssh
    short_options="1246AaCfgKkMNnqsTtVvXxYy"
elif [ "${program}" == scp ]; then
    program=scp
    short_options="12346BCpqrv"
else
    echo unknown program ${program}
    exit 1
fi

# parse arguments
prefix_args=()
suffix_args=()
userhost=
while test ${#} -gt 0
do
    arg=$1
    if [[ ${arg} == -* ]]; then
        arg=${arg#-}
        if [[ ${short_options} == *${arg}* ]]; then
            if [ "${arg}" == "v" ]; then
                verbose=3
            fi
            prefix_args+=("-${arg}")
            shift
        else
            prefix_args+=("-${arg}")
            prefix_args+=("$2")
            shift
            shift
        fi
    else
        userhost=$1
        first_arg=$1
        shift
        while test ${#} -gt 0
        do
            suffix_args+=("$1")
            shift
        done
    fi
done



# try to find the username
if [[ ! ${userhost} == *"@"* ]]; then
    if [ "${program}" == scp ]; then
        userhost=${suffix_args[@]: -1}
    fi
fi

if [[ ${userhost} == *"@"* ]]; then

    IFS='@' read -r -a array <<< "${userhost}"
    user=${array[0]}
    host=${array[1]}
    if [ "${program}" == scp ]; then
        IFS=':' read -r -a array <<< "${host}"
        host=${array[0]}
    fi
    if [ "${user}" == "git" ]; then
        # github arguments: git@github.com git-receive-pack 'ranlempow/git-hooks.git'
        IFS='/' read -r -a array <<< "${suffix_args[@]: -1}"
        user=${array[0]}
        len=${#suffix_args[@]}
        # add quote "'"
        suffix_args[${len} - 1]="'${suffix_args[${len} - 1]}'"
    fi

    # find the key file on the disk
    keypath=~/.ssh/namedkeys/${user}_rsa
    keypath="$(cd "$(dirname "${keypath}")"; pwd)/$(basename "${keypath}")"


    # echo ${prefix_args[@]}
    # echo ${user}
    # echo ${host}
    # echo ${suffix_args[@]}
    # echo ${ssh_exec}
    # echo ${keypath}
    # echo ${keypath}
fi

for _ssh_exec in $(type -ap "real${program}"); do
    if [ ${_ssh_exec} -ef $0 ]; then continue; fi
    ssh_exec=${_ssh_exec}
done
if [ -z ${ssh_exec} ]; then
    echo ssh executable ${ssh_exec} not found
    exit 1
fi

if [ ${verbose} -gt 3 ]; then
    echo user: ${user} 1>&2
    echo host: ${host} 1>&2
    echo ssh_exec: ${ssh_exec} 1>&2
    echo keypath: ${keypath} 1>&2
fi

if [ -f "${keypath}" ]; then
    ${ssh_exec} -i "${keypath}" ${prefix_args[@]} ${first_arg} ${suffix_args[@]}
else
    ${ssh_exec} ${prefix_args[@]} ${first_arg} ${suffix_args[@]}
fi

